/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jan_gruber_rawprocessor_model_engine_io_RawImageWriter */

#ifndef _Included_com_jan_gruber_rawprocessor_model_engine_io_RawImageWriter
#define _Included_com_jan_gruber_rawprocessor_model_engine_io_RawImageWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jan_gruber_rawprocessor_model_engine_io_RawImageWriter
 * Method:    writeDng
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[SIIIII[B)V
 */
JNIEXPORT void JNICALL Java_com_jan_1gruber_rawprocessor_model_engine_io_RawImageWriter_writeDng
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     com_jan_gruber_rawprocessor_model_engine_io_RawImageWriter
 * Method:    writeTiff
 * Signature: (Ljava/lang/String;[SIIIII)V
 */
    JNIEXPORT void JNICALL Java_com_jan_1gruber_rawprocessor_model_engine_io_RawImageWriter_exportTiff
    (JNIEnv *, jobject, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
